# Generated by Django 2.2.1 on 2019-05-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190513_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Conteúdo da pergunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Descrição breve'),
        ),
    ]
