# Generated by Django 2.2.1 on 2019-05-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20190524_1930'),
        ('question', '0003_auto_20190525_1717'),
    ]

    operations = [
    ]
