# Generated by Django 2.2.1 on 2019-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190529_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Breve descrição'),
        ),
    ]
